version: "3"
services:
  ethusdt:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p ethusdt
  adausdt:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p adausdt
