version: "3"
services:
  adabnb:
    image: cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p adabnb
  xlmbnb:
    image: cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p xlmbnb

