version: "3"
services:
  adabnb:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p adabnb
  xlmbnb:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p xlmbnb
  trxbnb:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p trxbnb

