version: "3"
services:
  adabnb:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p adabnb
  bnbeth:
    image: pjestin/cryptobot
    volumes:
      - .:/app/cryptobot
    environment:
      - command=bot_loop.py -p bnbeth
